### ISSUE TITLE
fail first attempt, error returned NameError: name 'requests' is not defined

### ISSUE THREAD

**Issue by seasaltseasalt** [luiseduardobr1/hathitrustPDF#1]
Hello: I hope you have time to help me. I installed success but received error message first attempt.  
Using on Mac 
Catalina 10.15.6 Anaconda Navigator 1.9.12
Jupyter Notebook 6.0.3

Collecting PyPDF2
  Downloading PyPDF2-1.26.0.tar.gz (77 kB)
     |████████████████████████████████| 77 kB 159 kB/s eta 0:00:01
Building wheels for collected packages: PyPDF2
  Building wheel for PyPDF2 (setup.py) ... done
  Created wheel for PyPDF2: filename=PyPDF2-1.26.0-py3-none-any.whl size=61084 sha256=aec0c43a520a17e0ad46cd62afbd29189caef3f99ef982a86b562c47f0065c82
  Stored in directory: /Users/xxx/Library/Caches/pip/wheels/b1/1a/8f/a4c34be976825a2f7948d0fa40907598d69834f8ab5889de11
Successfully built PyPDF2
Installing collected packages: PyPDF2
Successfully installed PyPDF2-1.26.0

=====
then entered the bookID where xxx is

"https://babel.hathitrust.org/cgi/pt?id=mdp.xxx"
r  = requests.get(link)

NameError                                 Traceback (most recent call last)
<ipython-input-1-323ed4a6067b> in <module>
      1 link = "https://babel.hathitrust.org/cgi/pt?id=mdp.xxx"
----> 2 r  = requests.get(link)

NameError: name 'requests' is not defined

checked install of package
Requirement already satisfied: PyPDF2 in /Users/XXX/opt/anaconda3/lib/python3.8/site-packages (1.26.0)

catalina forces anaconda into directory opt/anaconda3 rather than normal area.
maybe it has something to do with this.
It seems something is not right with my setup. Is requests standard with Anaconda? . Do you know where I look?

**Comment by luiseduardobr1** [comment]
Yes, ```requests``` is part of Anaconda standard packages. Try to reinstall or upgrade it using pip command-line:
```pip install --upgrade requests```. I have changed some lines of code, try again if it's running correctly.
