### ISSUE TITLE
the code is not working

### ISSUE THREAD

**Issue by Git-Vasanth** [luiseduardobr1/hathitrustPDF#10]
![Screenshot (5152)](https://github.com/luiseduardobr1/hathitrustPDF/assets/59464869/533e2c66-7082-4180-b8a9-cf83bcf3c242)
![Screenshot (5152)](https://github.com/luiseduardobr1/hathitrustPDF/assets/59464869/5213bc3e-bd48-44eb-b371-2a3517abcf4d)
C:\Users\Vasanth\AppData\Local\Programs\Python\Python312\python.exe C:\Users\Vasanth\Hathi_downs\hathitrustPDF.py 
C:\Users\Vasanth\Hathi_downs\hathitrustPDF.py:18: SyntaxWarning: invalid escape sequence '\w'
  id_book = re.findall('id=(\w*\.\d*)|$', link)[0]
C:\Users\Vasanth\Hathi_downs\hathitrustPDF.py:62: SyntaxWarning: invalid escape sequence '\D'
  key=lambda x: (int(re.sub('\D', '', x)), x))
Traceback (most recent call last):
  File "C:\Users\Vasanth\Hathi_downs\hathitrustPDF.py", line 23, in <module>
    pages_book = int(soup.find("section", {'class': 'd--reader--viewer'})['data-total-seq'])
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by AntonioBlaGra** [comment]
Same here: :-(

Traceback (most recent call last):
  File "/home/toni/Downloads/hathitrustPDF-master/hathitrustPDF.py", line 23, in <module>
    pages_book = int(soup.find("section", {'class': 'd--reader--viewer'})['data-total-seq'])
TypeError: 'NoneType' object is not subscriptable

**Comment by smorello87** [comment]
Same here, it looks like the structure of the HathiTrust rendering page has changed

Traceback (most recent call last):
  File "hathitrustPDF.py", line 23, in <module>
    pages_book = int(soup.find("section", {'class': 'd--reader--viewer'})['data-total-seq'])
TypeError: 'NoneType' object is not subscriptable

**Comment by ryanbugden** [comment]
It looks like @Midnight145 made a bunch of progress in updating the code, but HathiTrust has updated how they render the pages. See the README info: https://github.com/Midnight145/hathitrustPDF/tree/master

**Comment by Midnight145** [comment]
Yup. I'm not familiar enough with web development to continue it myself, but feel free to contribute to it if anyone has the knowhow to fix it.

**Comment by Midnight145** [comment]
Actually, looking into this, I might be able to work around it. I'll try and figure something out and update my repo if I can find anything.

**Comment by Midnight145** [comment]
Just pushed!! Realized I was wayyy overcomplicating things and I was trying to make things way harder than they needed to be. Only thing that was actually different was where the page count was located on the site.

**Comment by ryanbugden** [comment]
@Midnight145 Woo, nice, I'll check it out, thanks for looking into this!

**Comment by Midnight145** [comment]
No problem! Please open an issue on my end if you run into any troubles!

**Comment by ryanbugden** [comment]
@Midnight145 Looks to be working well on my end! For the future, you may need to enable issues on your fork to keep this one clean though.

Just learned how:
- Go to the Settings page of your fork.
- Click 'General' tab on the left
- Scroll down to the Features subsection
- Tick the Issues checkbox

**Comment by Midnight145** [comment]
Whoops, didn't realize that wasn't enabled. Will fix that real quick!
