### ISSUE TITLE
Acesso bloqueado pelo servidor

### ISSUE THREAD

**Issue by brunomioto** [luiseduardobr1/hathitrustPDF#4]
Oi Luís, tudo certo?

Tentei fazer um código parecido pelo R e o acesso foi negado pelo servidor após umas 4 páginas.

O seu código continua funcionando? Queria saber se tem algo que eu possa fazer.

Obrigado!

**Comment by emiranda-1988** [comment]
Hi Luis,

I’ve tried this code on my Windows laptop, even though I downloaded BeautifulSoup4; but the errors keep on appearing.

**Comment by emiranda-1988** [comment]
Could you please help me with a Hathitrust book/magazine by making a video? Thank you so much
